instruments:
  - type: ganged_vertical_bar_gauge
    gang_type: horizontal
    ratio: 0.2
    row: 0
    column: 0
    span:
      rows: 40
      columns: 30 
    groups:
      - name: CHT
        gap: 0
        instruments:
            -
              preferences: BAR15
            -
              preferences: BAR16
            -
              preferences: BAR17
            -
              preferences: BAR18

