instruments:
  - type: ganged_vertical_bar_gauge
    gang_type: horizontal
    ratio: 0.2
    row: 0
    column: 0
    span:
      rows: 40
      columns: 30 
    groups:
      - name: EGT
        gap: 0
        instruments:
            -
              preferences: BAR11
            -
              preferences: BAR12
            -
              preferences: BAR13
            -
              preferences: BAR14

