instruments:
  - type: vertical_bar_gauge
    row: 0
    column: 0
    span:
      rows: 20
      columns: 6
    options:
      name: Dimmer 
      decimal_places: 0
      show_units: false
      show_value: false
      dbkey: DIM
      bar_width_percent: 0.5
  - type: button
    row: 0
    column: 0
    span:
      rows: 10
      columns: 6
    options:
      config: buttons/dimmer-up-invisible.yaml
  - type: button
    row: 10
    column: 0
    span:
      rows: 10
      columns: 6
    options:
      config: buttons/dimmer-down-invisible.yaml

