instruments:
  - type: include,includes/mgl/v16/radio-volumes-controls-display.yaml
    row: 0
    column: 0
    span:
      rows: 38
      columns: 29
  - type: static_text
    row: 0
    column: 29
    span:
      rows: 5
      columns: 20
    preferences: TEXT3
    options:
      text: "Active:"
      font_mask: "XXXXXXX:"
      alignment: AlignLeft
  - type: static_text
    row: 0
    column: 68
    span:
      rows: 5
      columns: 20
    preferences: TEXT4
    options:
      text: "Standby:"
      font_mask: "XXXXXXX:"
      alignment: AlignLeft
  - type: include,includes/mgl/v16/square-active-radio-display.yaml
    row: 5
    column: 28
#    span:
#      rows: 27
#      columns: 42
  - type: include,includes/mgl/v16/square-standby-radio-display.yaml
    row: 5
    column: 66
  - type: button
    row: 5
    column: 59
    span:
      rows: 6
      columns: 7
    move:
      shrink: 12
    options:
      config: buttons/mgl/v16/swap-active-standby.yaml
      font_mask: "SWAP"
      encoder_order: 400026
  - type: include,lists/radio/listbox.yaml
    row: 0
    column: 101
    span:
      rows: 40
      columns: 54

