type: toggle
text: "AP\nAdjust"
dbkey: TSBTN{id}24
condition_keys:
  - MAVMODE
  - MAVSTATE
  - MAVADJ
conditions:
  - when: "MAVMODE eq 'TRIM'"
    actions:
      - button: disable
      - set bg color: darkgray
      - button: unchecked
      - set value: MAVADJ, false
  - when: "MAVSTATE eq 'ARMED' and MAVMODE ne 'TRIM'"
    actions:
      - button: enable
      - set bg color: lightgray
    continue: true
  - when: "CLICKED eq true and DBKEY eq false and MAVMODE ne 'TRIM'"
    actions:
      - set bg color: orange
      - button: unchecked
      - set value: MAVADJ, false
  - when: "CLICKED eq true and DBKEY eq true and MAVMODE ne 'TRIM'"
    actions:
      - set bg color: orange
      - button: checked
      - set value: MAVADJ, true
  - when: "MAVADJ eq true and MAVMODE ne 'TRIM'"
    actions:
      - set bg color: green
      - button: checked
  - when: "MAVADJ eq false"
    actions:
      - button: unchecked
