type: toggle
text: "Heading\nHold"
dbkey: TSBTN{id}25
condition_keys:
  - APMODE
  - APSTAT
  - APREQ
conditions:
  - when: "APSTAT ne 'ARMED'"
    actions:
      - button: disable
      - set bg color: red
      - button: unchecked
  - when: "APSTAT eq 'ARMED'"
    actions:
      - button: enable
    continue: true
  - when: "APMODE ne 'CRUISE' and APREQ ne 'CRUISE'"
    actions:
      - set bg color: lightgray
      - button: unchecked
    continue: true
  - when: "CLICKED eq true and DBKEY eq false and APMODE eq 'CRUISE' and APREQ eq 'CRUISE'"
    # We are in cruise, requested mode is cruise but the button is off, drop to TRIM
    actions:
      - set value: APREQ, TRIM
      - set bg color: orange
  - when: "CLICKED eq true and DBKEY eq true and APMODE ne 'CRUISE'"
    # We a are on, FP is off, we are armed and not in cruise mode like we should be
    actions:
      - set value: APREQ, CRUISE
      - set bg color: orange
  - when: "CLICKED eq false and APMODE eq 'CRUISE' and [APREQ eq 'CRUISE' or APREQ eq 'INIT']"
    # We have transitioned to cruise mode
    actions:
      - set bg color: green
      - button: checked


