type: toggle
text: "AP\nAdjust"
dbkey: TSBTN{id}24
condition_keys:
  - MAVMODE
  - MAVSTATE
  - MAVADJ
  - MAVREQADJ
conditions:
  - when: "MAVMODE eq 'TRIM'"
    actions:
      - button: disable
      - set bg color: darkgray
      - button: unchecked
        # Maybethis should be done in the mavlink plugin?
      - set value: MAVREQADJ, false
  - when: "MAVSTATE eq 'ARMED' and MAVMODE ne 'TRIM' and MAVADJ eq true"
    actions:
      - set bg color: green
      - button: checked
      - button: enabled
    continue: true
  - when: "MAVSTATE eq 'ARMED' and MAVMODE ne 'TRIM' and MAVADJ eq false"
    actions:
      - set bg color: lightgray
      - button: unchecked
      - button: enable
    continue: true
  - when: "CLICKED eq true and DBKEY eq false and MAVMODE ne 'TRIM'"
    actions:
      - set bg color: orange
      - set value: MAVREQADJ, false
  - when: "CLICKED eq true and DBKEY eq true and MAVMODE ne 'TRIM'"
    actions:
      - set bg color: orange
      - set value: MAVREQADJ, true


