type: simple
text: ""
dbkey: TSBTN{id}13
conditions:
  - when: "SCREEN eq 'SIXPACK'"
    actions:
      - set text: PFD
      - set bg color: lightgray
    continue: true
  - when: "SCREEN ne 'SIXPACK'"
    actions:
      - set text: "SIX\nPACK"
      - set bg color: lightgray
    continue: true
  - when: "CLICKED eq true and [ SCREEN ne 'SIXPACK' ]"
    actions:
      - show screen: SIXPACK
  - when: "CLICKED eq true and SCREEN eq 'SIXPACK'"
    actions:
      - show screen: PFD

