type: simple
text: ""
dbkey: TSBTN{id}19
hover_show: True
condition_keys:
- HIDEBUTTON
conditions:
  - when: "SCREEN eq 'ANDROID' and not HIDEBUTTON"
    actions:
      - set text: PFD
      - set bg color: lightgray
      - set fg color: black
    continue: true
  - when: "SCREEN ne 'ANDROID' and not HIDEBUTTON"
    actions:
      - set text: ANDROID
      - set bg color: lightgray
      - set fg color: black
    continue: true
  - when: "HIDEBUTTON"
    actions:
      - set bg color: "#00000000"
      - set fg color: "#00000000"
  - when: "CLICKED eq true and SCREEN ne 'ANDROID'" 
    actions:
      - show screen: ANDROID
  - when: "CLICKED eq true and SCREEN eq 'ANDROID'"
    actions:
      - show screen: PFD

