type: simple
text: "EMS"
dbkey: BTN6
conditions:
  - when: "CLICKED eq true" 
    actions:
      - show next screen: true
  - when: "SCREEN eq 'EMS'"
    actions:
      - set bg color: orange
  - when: "SCREEN ne 'EMS'"
    actions:
      - set bg color: lightgrey

