type: simple
text: ""
dbkey: TSBTN{id}20
hover_show: True
condition_keys:
  - CHT11
  - CHT12
  - CHT13
  - CHT14
  - EGT11
  - EGT12
  - EGT13
  - EGT14
  - HIDEBUTTON
conditions:
  - when: "SCREEN eq 'EMS2' and not HIDEBUTTON"
    actions:
      - set text: PFD
      - set bg color: lightgray
      - set fg color: black
    continue: true
  - when: "SCREEN ne 'EMS2' and not HIDEBUTTON"
    actions:
      - set text: EMS2
      - set bg color: lightgray
      - set fg color: black
    continue: true
  - when: "SCREEN ne 'EMS2' and [ CHT11.annunciate or CHT12.annunciate or CHT13.annunciate or CHT14.annunciate or EGT11.annunciate or EGT12.annunciate or EGT13.annunciate or EGT14.annunciate ]"
    actions:
      - set text: EMS2
      - set bg color: red
      - set fg color: black
    continue: true
  - when: "HIDEBUTTON and not PREVIOUS_CONDITION"
    actions:
      - set bg color: "#00000000"
      - set fg color: "#00000000"
  - when: "CLICKED eq true and SCREEN ne 'EMS2'"
    actions:
      - show screen: EMS2
      - set value: HIDEBUTTON,False
  - when: "CLICKED eq true and SCREEN eq 'EMS2'"
    actions:
      - show screen: PFD
      - set value: HIDEBUTTON,False

