instruments:
  - type: ganged_arc_gauge
    gang_type: horizontal
    groups:
      - name: Power and Temp
        instruments:
          -
            preferences: ARC9
          -
            preferences: ARC10
          -
            preferences: ARC11
          -
            preferences: ARC12

