ANDROID:
  module: pyefis.screens.screenbuilder
  title: Screen Builder
  include:
  - hmi/encoder_input.yaml
  layout:
    #draw_grid: true
    rows: 110
    columns: 200
    display_state:
      interval: 3000
      states: 2
  instruments:
    - type: value_text
      row: 100
      column: 0
      span:
        rows: 10
        columns: 155
      options:
        dbkey: APMSG
        font_percent: 0.9
    - type: weston
      #disabled: true
      row: 0
      column: 0
      span:
        rows: 100
        columns: 155
      options:
        socket: pyefis-waydroid-1
        ini: weston.ini
        command: waydroid
        args:
          - show-full-ui
    - type: include,includes/arcs/vertical/four_high_two_states.yaml
      row: 0
      column: 155
    - type: include,BUTTON_GROUP1
      row: 0
      column: 186
    - type: include,includes/bars/vertical/fuel_info_FUELP1-FUELF1-FUELQT-FUELQ1-FUELQ2-FUELQ3.yaml
      row: 70
      column: 155
      display_state: 1
    - type: include,includes/mgl/v16/square-active-radio-display.yaml
      row: 70
      column: 156
      span:
        rows: 40
        columns: 45
      display_state: 2
      replace:
        radio_id: 1

