ANDROID:
  module: pyefis.screens.screenbuilder
  title: Screen Builder
  include:
  - hmi/encoder_input.yaml
  layout:
    #draw_grid: true
    rows: 110
    columns: 200
  instruments:
    - type: value_text
      row: 100
      column: 0
      span:
        rows: 10
        columns: 155
      options:
        dbkey: APMSG
        font_percent: 0.9
    - type: weston
      #disabled: true
      row: 0
      column: 0
      span:
        rows: 100
        columns: 155
      options:
        socket: pyefis-waydroid-1
        ini: weston.ini
        command: waydroid
        args:
          - show-full-ui
    - type: include,includes/arcs/vertical/ds1_TACH1-OILP1-HTOT1-VOLT_ds2_TACH1-OILT1-OAT-CURRNT.yaml
      row: 0
      column: 155
    - type: include,includes/buttons/vertical/screen_changing_PFD-EMS-EMS2-ANDROID-RADIO-SIXPACK-Units.yaml
      row: 0
      column: 186
    - type: include,includes/bars/vertical/fuel_info_FUELP1-FUELF1-FUELQT-FUELQ1-FUELQ2-FUELQ3.yaml
      row: 70
      column: 155
