# Example primary flight display
PFD:
  include:
  - screens/virtualvfr_db.yaml
  - hmi/encoder_input.yaml
    #refresh_period: 0.25
  module: pyefis.screens.screenbuilder
  title: Screen Builder
  layout:
    #draw_grid: true
    rows: 110
    columns: 200
    display_state:
      interval: 3000
      states: 2
  instruments:
    - type: include,includes/ahrs/virtual_vfr.yaml
      row: 0
      column: 0
    - type: include,includes/arcs/vertical/ds1_TACH1-OILP1-HTOT1-VOLT_ds2_TACH1-OILT1-OAT-CURRNT-segmented.yaml
      row: 0
      column: 155
    - type: include,includes/buttons/vertical/screen_changing_PFD-EMS-EMS2-ANDROID-RADIO-SIXPACK-Units.yaml
      row: 0
      column: 186
    - type: include,includes/bars/vertical/fuel_info_FUELP1-FUELF1-FUELQT-FUELQ1-FUELQ2-FUELQ3-segmented.yaml
      row: 70
      column: 155
      display_state: 1
    - type: include,includes/mgl/v16/square-active-radio-display-dseg.yaml
      row: 70
      column: 156
      span:
        rows: 40
        columns: 45
      display_state: 2
      replace:
        radio_id: 1

