# Example primary flight display
PFD:
  include:
  - screens/virtualvfr_db.yaml
  - hmi/encoder_input.yaml
    #refresh_period: 0.25
  module: pyefis.screens.screenbuilder
  title: Screen Builder
  layout:
    #draw_grid: true
    rows: 110
    columns: 200
    display_state:
      interval: 3000
      states: 2
  instruments:
    - type: include,includes/virtual_vfr.yaml
      row: 0
      column: 0
    - type: include,includes/basic_arcs.yaml
      row: 0
      column: 155
    - type: include,includes/side-buttons.yaml
      row: 0
      column: 186
    - type: include,includes/fuel_gauges.yaml
      row: 70
      column: 155
      display_state: 1
    - type: include,includes/mgl/v16/active-display.yaml
      row: 70
      column: 156
      span:
        rows: 40
        columns: 45
      display_state: 2
      replace:
        radio_id: 1

