# This is a work in progress for a radio interface
# Eric plans to purchase an MGL V16 radio, once in hand 
# development on this feature will continue
RADIO:
  include:
  - screens/virtualvfr_db.yaml
  - hmi/encoder_input.yaml
  module: pyefis.screens.screenbuilder
  title: Radio Screen
  layout:
    rows: 110
    columns: 200
    #draw_grid: true
  instruments:
    - type: value_text
      row: 101
      column: 30
      span:
        rows: 9
        columns: 60
      options:
        dbkey: APMSG
        font_percent: 0.9
    - type: include,includes/virtual_vfr.yaml
      disabled: false
      row: 0
      column: 0
      span:
        rows: 70
        columns: 125
    - type: include,includes/basic_arcs.yaml
      row: 0
      column: 155
    - type: include,includes/power_temp_arcs.yaml
      row: 0
      column: 125
    - type: include,includes/side-buttons.yaml
      row: 0
      column: 186
    - type: include,includes/fuel_gauges.yaml
      row: 70
      column: 155
    - type: include,includes/mgl/v16/radio-display.yaml
      replace:
        radio_id: 1 # {radio_id} is replaced anywhere it appears in the included config
                    # Maybe you have two radios COMACTTX{radio_id} -> COMACTTX1
      row: 70
      column: 0
    - type: include,includes/mgl/v16/radio-display.yaml
      disabled: true
      replace:
        radio_id: 2 # {radio_id} is replaced anywhere it appears in the included config
                    # Maybe you have two radios COMACTTX{radio_id} -> COMACTTX1
      row: 0
      column: 0
      span:
        rows: 18
        columns: 75

