SIXPACK:
  module: pyefis.screens.screenbuilder
  title: Standard Instrument Panel New
  include:
  - hmi/encoder_input.yaml
  layout:
    rows: 110
    columns: 200
    draw_grid: false
  instruments:
    - type: include,BUTTON_GROUP1
      row: 0
      column: 186
    -
      type: airspeed_dial
      row: 0
      column: 0
      span:
        rows: 50
        columns: 62
      options:
        bg_color: "#00000000"
    - type: atitude_indicator
      row: 0
      column: 62
      span:
        rows: 50
        columns: 62
    -
      type: altimeter_dial
      row: 0
      column: 124
      span:
        rows: 50
        columns: 62
      options:
        altitude: true
    -
      type: turn_coordinator
      row: 50
      column: 0
      span:
        rows: 50
        columns: 62
    - 
      type: horizontal_situation_indicator
      row: 50
      column: 62
      span:
        rows: 50
        columns: 62
      move:
        shrink: 11
        justify:
          - bottom
      options:
        gsi_enabled: true
        cdi_enabled: true
        font_percent: 0.07
    -
      type: heading_display
      column: 86
      row: 50
      span:
        rows: 5
        columns: 14
    -
      type: vsi_dial
      row: 50
      column: 124
      span:
        rows: 50
        columns: 62
    - type: value_text
      row: 100
      column: 60
      span:
        rows: 10
        columns: 140
      options:
        dbkey: MAVMSG
        font_percent: 0.9
