ANDROID:
  module: pyefis.screens.screenbuilder
  title: Screen Builder
  include:
  - HMI_ENCODER_BUTTONS
  layout:
    #draw_grid: true
    rows: 110
    columns: 200
    display_state:
      interval: 3000
      states: 2
  instruments:
    - type: value_text
      disabled: DEMO_TESTING_TEXT
      row: 0
      column: 0
      span:
        rows: 2
        columns: 200
      options:
        dbkey: MAVMSG
        font_percent: 0.9
    - type: weston
      disabled: DEMO_TESTING_TEXT
      row: 2
      column: 0
      span:
        rows: 43
        columns: 200
      options:
        socket: pyefis-waydroid-1
        ini: weston.ini
        command: waydroid
        args:
          - show-full-ui
    - type: weston
      disabled: not DEMO_TESTING_TEXT
      row: 0
      column: 0
      span:
        rows: 45
        columns: 200
      options:
        socket: pyefis-waydroid-1
        ini: weston.ini
        command: waydroid
        args:
          - show-full-ui
    - type: include,includes/arcs/horizontal/four_wide_two_states_preferences_ARC1-8.yaml
      disabled: BUTTONS
      row: 45
      column: 0
      span:
        columns: 195.5
        rows: 15
    - type: include,includes/arcs/vertical/four_high_two_states_preferences_ARC1-8.yaml
      disabled: not BUTTONS
      row: 45
      column: 0
      span:
        columns: 195.5
        rows: 15
    - type: include,BUTTON_GROUP2
      disabled: BUTTONS
      row: 100
      column: 0
    - type: include,includes/bars/vertical/six_wide_preferences_BAR1-6.yaml
      row: 60
      column: 0
      display_state: 1
      span:
        rows: 40
        columns: 200
    - type: include,includes/mgl/v16/square-active-radio-display.yaml
      row: 60
      column: 0
      span:
        rows: 40
        columns: 200
      display_state: 2
      replace:
        radio_id: 1

