EMS:
  include:
  - screens/virtualvfr_db.yaml
  - HMI_ENCODER_BUTTONS
  module: pyefis.screens.screenbuilder
  title: Engine Management New
  layout:
    rows: 110
    columns: 200
    draw_grid: false
  instruments:
    - type: value_text
      disabled: DEMO_TESTING_TEXT
      row: 100
      column: 00
      span:
        rows: 10
        columns: 80
      options:
        dbkey: MAVMSG
        font_percent: 0.9
    - type: include,includes/ahrs/virtual_vfr.yaml
      row: 0
      column: 0
      span:
        rows: 45
        columns: 200
    - type: include,includes/arcs/horizontal/four_wide_two_states_preferences_ARC1-8.yaml
      disabled: BUTTONS
      row: 45
      column: 0
      span:
        columns: 195.5
        rows: 15
    - type: include,includes/arcs/horizontal/four_wide_two_states_preferences_ARC1-8.yaml
      disabled: not BUTTONS
      row: 45
      column: 0
      span:
        columns: 195.5
        rows: 15
    - type: include,includes/arcs/horizontal/four_wide_one_state_preferences_ARC9-12.yaml
      disabled: BUTTONS
      row: 60
      column: 0
      span:
        columns: 195.5
        rows: 15
    - type: include,includes/arcs/vertical/four_high_one_state_preferences_ARC9-12.yaml
      disabled: not BUTTONS
      row: 60
      column: 0
      span:
        columns: 195.5
        rows: 15
    - type: include,BUTTON_GROUP1
      disabled: BUTTONS 
      row: 100
      column: 0
#    - type: include,includes/bars/vertical/six_wide_preferences_BAR1-6.yaml
#      row: 75
#      column: 0
    - type: include,includes/bars/vertical/4_CHT.yaml
      row: 75
      column: 100
      span:
        rows: 20
        columns: 100
    - type: include,includes/bars/vertical/4_EGT.yaml
      row: 75
      column: 0
      span:
        rows: 20
        columns: 100
    - type: ganged_button
      #disabled: true
      gang_type: horizontal
      row: 95.5
      column: 5
      #move:
      #  shrink: 25
      #  justify: top
      span:
        rows: 4
        columns: 100
      groups:
        - name: Buttons
          gap: 2
          common_options:
            font_mask: Normalize
          instruments:
            -
              options:
                config: buttons/egt-Normalize.yaml
                encoder_order: 600031
            -
              options:
                config: buttons/egt-Lean.yaml
                encoder_order: 600032
            -
              options:
                config: buttons/egt-Peak.yaml
                encoder_order: 600033
            -
              options:
                config: buttons/egt-reset-peak.yaml
                encoder_order: 600034
    -
      type: ganged_vertical_bar_gauge
      gang_type: horizontal
      disabled: DEMO_TESTING_TEXT
      row: 70
      column: 0
      span:
        rows: 30
        columns: 80
      groups:
        - name: RPM
          gap: 0
          instruments:
            -
              preferences: BAR28
            -
              preferences: BAR29
        - name: Engine
          gap: 0
          instruments:
            -
              preferences: BAR22
            -
              preferences: BAR23
            -
              preferences: BAR24
            -
              preferences: BAR25
            -
              preferences: BAR26

        - name: Temps
          gap: 0
          instruments:
            -
              preferences: BAR27

    -
      type: ganged_vertical_bar_gauge
      disabled: true #not DEMO_TESTING_TEXT
      ratio: 0.2
      gang_type: horizontal
      row: 72
      column: 0
      span:
        rows: 38
        columns: 80
      groups:
        - name: RPM
          gap: 0
          common_options:
            bar_width_percent: 0.5
            line_width_percent: 0.7
            text_gap: 8
            small_font_percent: 0.060
            big_font_percent: 0.085
          instruments:
            -
              preferences: BAR28
            -
              preferences: BAR29
        - name: Engine
          common_options:
            bar_width_percent: 0.5
            line_width_percent: 0.7
            text_gap: 8
            small_font_percent: 0.060
            big_font_percent: 0.085
          gap: 0
          instruments:
            -
              preferences: BAR22
            -
              preferences: BAR23
            -
              preferences: BAR24
            -
              preferences: BAR25
            -
              preferences: BAR26
        - name: Temps
          common_options:
            bar_width_percent: 0.5
            line_width_percent: 0.7
            text_gap: 8
            small_font_percent: 0.060
            big_font_percent: 0.085
          gap: 0
          instruments:
          gap: 0
          instruments:
            -
              preferences: BAR27

