EMS:
  include:
  - screens/virtualvfr_db.yaml
  - HMI_ENCODER_BUTTONS
  module: pyefis.screens.screenbuilder
  title: Engine Management New
  layout:
    rows: 110
    columns: 200
    draw_grid: false
  instruments:
    - type: value_text
      disabled: DEMO_TESTING_TEXT
      row: 100
      column: 0
      span:
        rows: 10
        columns: 80
      options:
        dbkey: MAVMSG
        font_percent: 0.9
    - type: include,includes/ahrs/virtual_vfr.yaml
      row: 0
      column: 75
      span:
        rows: 70
        columns: 125
    - type: include,includes/arcs/vertical/four_high_two_states_preferences_ARC1-8.yaml
      disabled: BUTTONS
      row: 0
      column: 44.5
      span:
        columns: 30
        rows: 70
    - type: include,includes/arcs/vertical/four_high_two_states_preferences_ARC1-8.yaml
      disabled: not BUTTONS
      row: 0
      column: 37
      span:
        columns: 37.5
        rows: 70
    - type: include,includes/arcs/vertical/four_high_one_state_preferences_ARC9-12.yaml
      disabled: BUTTONS
      row: 0
      column: 14.5
      span:
        columns: 30
        rows: 70
    - type: include,includes/arcs/vertical/four_high_one_state_preferences_ARC9-12.yaml
      disabled: not BUTTONS
      row: 0
      column: 14.5
      span:
        columns: 37.5
        rows: 70
    - type: include,BUTTON_GROUP1
      disabled: BUTTONS
      row: 0
      column: 0
    - type: include,includes/bars/vertical/six_wide_preferences_BAR1-6.yaml
      row: 70
      column: 155
    - type: include,includes/bars/vertical/4_CHT.yaml
      row: 70
      column: 123
      span:
        rows: 40
        columns: 30
    - type: include,includes/bars/vertical/4_EGT.yaml
      row: 70
      column: 91
      span:
        rows: 40
        columns: 30
    - type: ganged_button
      #disabled: true
      gang_type: vertical
      row: 74
      column: 80
      #move:
      #  shrink: 25
      #  justify: top
      span:
        rows: 30
        columns: 10
      groups:
        - name: Buttons
          gap: 12
          common_options:
            font_mask: Normalize
          instruments:
            -
              options:
                config: buttons/egt-Normalize.yaml
                encoder_order: 600031
            -
              options:
                config: buttons/egt-Lean.yaml
                encoder_order: 600032
            -
              options:
                config: buttons/egt-Peak.yaml
                encoder_order: 600033
            -
              options:
                config: buttons/egt-reset-peak.yaml
                encoder_order: 600034
    -
      type: ganged_vertical_bar_gauge
      disabled: DEMO_TESTING_TEXT
      gang_type: horizontal
      row: 70
      column: 0
      span:
        rows: 30
        columns: 80
      groups:
        - name: RPM
          gap: 0
          instruments:
            -
              preferences: BAR28
            -
              preferences: BAR29
        - name: Engine
          gap: 0
          instruments:
            -
              preferences: BAR22
            -
              preferences: BAR23
            -
              preferences: BAR24
            -
              preferences: BAR25
            -
              preferences: BAR26

        - name: Temps
          gap: 0
          instruments:
            -
              preferences: BAR27
    -
      type: ganged_vertical_bar_gauge
      disabled: not DEMO_TESTING_TEXT
      ratio: 0.2
      gang_type: horizontal
      row: 72
      column: 0
      span:
        rows: 38
        columns: 80
      groups:
        - name: RPM
          gap: 0
          common_options:
            bar_width_percent: 0.5
            line_width_percent: 0.7
            text_gap: 8
            small_font_percent: 0.060 
            big_font_percent: 0.085   
          instruments:
            -
              preferences: BAR28
            -
              preferences: BAR29
        - name: Engine
          common_options:
            bar_width_percent: 0.5
            line_width_percent: 0.7
            text_gap: 8
            small_font_percent: 0.060
            big_font_percent: 0.085
          gap: 0
          instruments:
            -
              preferences: BAR22
            -
              preferences: BAR23
            -
              preferences: BAR24
            -
              preferences: BAR25
            -
              preferences: BAR26

        - name: Temps
          common_options:
            bar_width_percent: 0.5
            line_width_percent: 0.7
            text_gap: 8
            small_font_percent: 0.060
            big_font_percent: 0.085
          gap: 0
          instruments:
          gap: 0
          instruments:
            -
              preferences: BAR27

