EMS2:
  include: HMI_ENCODER_BUTTONS
  module: pyefis.screens.screenbuilder
  title: Engine Management New
  layout:
    rows: 110
    columns: 200
    draw_grid: false
  instruments:
    - type: value_text
      disabled: DEMO_TESTING_TEXT
      row: 100
      column: 80
      span:
        rows: 10
        columns: 140
      options:
        dbkey: MAVMSG
        font_percent: 0.9
    - type: ganged_button
      gang_type: horizontal
      row: 68
      column: 80
#        move:
#          shrink: 25
#          justify: top
      span:
        rows: 4
        columns: 110
      groups:
        - name: Buttons
          gap: 4
          instruments:
            -
              options:
                config: buttons/egt-Normalize.yaml
            -
              options:
                config: buttons/egt-Lean.yaml
            -
              options:
                config: buttons/egt-Peak.yaml
            -
              options:
                config: buttons/egt-reset-peak.yaml
    -
      type: arc_gauge
      row: 0
      column: 0
      span:
        rows: 25
        columns: 99
      preferences: ARC13
    -
      type: arc_gauge
      row: 0
      column: 100
      span:
        rows: 25
        columns: 99
      preferences: ARC14
    -
      type: ganged_horizontal_bar_gauge
      disabled: BUTTONS
      gang_type: horizontal
      row: 25
      column: 0
      span:
        rows: 15
        columns: 200
      groups:
        - name: Oil
          gap: 2
          instruments:
            -
              preferences: BAR7
            -
              preferences: BAR8
    -
      type: ganged_horizontal_bar_gauge
      disabled: not BUTTONS
      gang_type: vertical
      row: 25
      column: 0
      span:
        rows: 15
        columns: 200
      groups:
        - name: Oil
          gap: 2
          instruments:
            -
              preferences: BAR7
            -
              preferences: BAR8

    -
      type: static_text
      row: 40
      column: 20
      span:
        columns: 30
        rows: 2
      options:
        text: Power
    -
      type: static_text
      row: 40
      column: 130
      span:
        columns: 30
        rows: 2
      options:
        text: EGT
    -
      type: static_text
      row: 72.5
      column: 50
      span:
        columns: 30
        rows: 2
      options:
        text: CHT
    -
      type: static_text
      row: 72.5
      column: 150
      span:
        columns: 30
        rows: 2
      options:
        text: FUEL
    -
      type: ganged_vertical_bar_gauge
      disabled: BUTTONS
      gang_type: horizontal
      ratio: 0.2
      row: 43
      column: 0
      span:
        rows: 24
        columns: 200
      groups:
        - name: Power
          instruments:
            -
              preferences: BAR9
            -
              preferences: BAR10
        - name: EGT
          instruments:
            -
              preferences: BAR11
            -
              preferences: BAR12
            -
              preferences: BAR13
            -
              preferences: BAR14

    -
      type: ganged_vertical_bar_gauge
      disabled: BUTTONS
      gang_type: horizontal
      ratio: 0.2
      row: 76
      column: 0
      span:
        rows: 24
        columns: 200
      groups:
        - name: CHT
          instruments:
            -
              preferences: BAR15
            -
              preferences: BAR16
            -
              preferences: BAR17
            -
              preferences: BAR18
        - name: FUEL
          instruments:
            -
              preferences: BAR19
            -
              preferences: BAR20
            -
              preferences: BAR21
    -
      type: ganged_vertical_bar_gauge
      disabled: not BUTTONS
      gang_type: horizontal
      ratio: 0.2
      row: 51
      column: 0
      span:
        rows: 50
        columns: 200
      groups:
        - name: Power
          instruments:
            -
              preferences: BAR9
            -
              preferences: BAR10
        - name: EGT
          instruments:
            -
              preferences: BAR11
            -
              preferences: BAR12
            -
              preferences: BAR13
            -
              preferences: BAR14
        - name: CHT
          instruments:
            -
              preferences: BAR15
            -
              preferences: BAR16
            -
              preferences: BAR17
            -
              preferences: BAR18
        - name: FUEL
          instruments:
            -
              preferences: BAR19
            -
              preferences: BAR20
            -
              preferences: BAR21

    - type: include,BUTTON_GROUP1
      disabled: BUTTONS
      row: 100
      column: 0

