# Example primary flight display
PFD:
  include:
  - screens/virtualvfr_db.yaml
  - HMI_ENCODER_BUTTONS
    #refresh_period: 0.25
  module: pyefis.screens.screenbuilder
  title: Screen Builder
  layout:
    #draw_grid: true
    rows: 110
    columns: 200
    display_state:
      interval: 3000
      states: 2
  instruments:
    - type: include,includes/ahrs/virtual_vfr.yaml
      row: 0
      column: 0
    - type: include,includes/arcs/vertical/four_high_two_states_preferences_ARC1-8.yaml
      disabled: BUTTONS
      row: 0
      column: 155
      span:
        columns: 30
        rows: 70
    - type: include,includes/arcs/vertical/four_high_two_states_preferences_ARC1-8.yaml
      disabled: not BUTTONS
      row: 0
      column: 155
      span:
        columns: 45
        rows: 70
    - type: include,BUTTON_GROUP1
      disabled: BUTTONS 
      row: 0
      column: 185.5
    - type: include,includes/bars/vertical/six_wide_preferences_BAR1-6.yaml
      row: 70
      column: 155
      display_state: 1
    - type: include,includes/mgl/v16/square-active-radio-display.yaml
      row: 70
      column: 156
      span:
        rows: 40
        columns: 45
      display_state: 2
      replace:
        radio_id: 1

