instruments:
  - type: ganged_vertical_bar_gauge
    gang_type: horizontal
    ratio: 0.2
    groups:
      - name: EGT
        gap: 0
        instruments:
            -
              preferences: BAR11
              options: 
                disabled: CYLINDER_1
            -
              preferences: BAR12
              options:
                disabled: CYLINDER_2
            -
              preferences: BAR13
              options:
                disabled: CYLINDER_3
            -
              preferences: BAR14
              options:
                disabled: CYLINDER_4

