instruments:
  - type: include,RADIO_VOLUMES
    row: 0
    column: 0
    span:
      rows: 38
      columns: 29
  - type: static_text
    row: 0
    column: 29
    span:
      rows: 5
      columns: 27
    preferences: TEXT3
    options:
      text: "Active:"
      font_mask: "XXXXXXX:"
      alignment: AlignLeft
  - type: static_text
    row: 0
    column: 64
    span:
      rows: 5
      columns: 27
    preferences: TEXT4
    options:
      text: "Standby:"
      font_mask: "XXXXXXX:"
      alignment: AlignLeft
  - type: include,RADIO_ACTIVE
    row: 5
    column: 28
#    span:
#      rows: 27
#      columns: 42
  - type: include,RADIO_STANDBY
    row: 5
    column: 64
  - type: button
    row: 26
    column: 64
    span:
      rows: 6
      columns: 6
    #move:
    #  shrink: 14
    options:
      config: buttons/mgl/v16/swap-active-standby.yaml
      font_mask: "SWAP"
      encoder_order: 400026
  - type: include,RADIO_LISTBOX
    row: 0
    column: 100
    span:
      rows: 40
      columns: 55

