type: simple
text: "L"
dbkey: TSBTN{id}16
condition_keys:
  - LEADER
conditions:
  - when: "LEADER eq true"
    actions:
      - button: disable
      - set text: L
      - set bg color: green
  - when: "LEADER eq false"
    actions:
      - button: disable
      - set text: F
      - set bg color: red

