instruments:
  - type: ganged_button
    gang_type: vertical
    row: 0
    column: 0
    span:
      rows: 70
      columns: 14.5
    groups:
      - name: Side Buttons
        gap: 6
        common_options:
            font_mask: "ANDROID"
        instruments:
          -
            options:
              config: buttons/screen-ems-pfd.yaml
          -
            options:
              config: buttons/screen-ems2-pfd.yaml
          -
            options:
              config: buttons/screen-android-pfd.yaml
          -
            options:
              config: buttons/screen-radio-pfd.yaml
          -
            options:
              config: buttons/screen-sixpack-pfd.yaml
          -
            options:
              config: buttons/units.yaml
