instruments:
  - type: virtual_vfr
    row: 0
    column: 0
    span:
      rows: 110
      columns: 155
    options: 
      font_percent: 0.025
  - type: horizontal_situation_indicator
    row: 0
    column: 0
    span:
      rows: 110
      columns: 155
    move:
      shrink: 12
    options:
      #fontSize: 48
      font_percent: 0.05
      fgcolor: "#aaaaaa"
      bgcolor: "#aaaaaa"
      cdi_enabled: true
      gsi_enabled: true
  - type: altimeter_tape
    row: 0
    column: 140
    span:
      rows: 110
      columns: 15
    options:
      #fontsize: 28
      font_percent: 0.24
      #number_font_size: 40
      altitude: true
  - type: vsi_pfd
    row: 0
    column: 130
    span:
      rows: 50
      columns: 10
  - type: numeric_display
    row: 50
    column: 128.5
    span:
      rows: 5
      columns: 12
    options:
      font_mask: "0000"
      decimalPlaces: 0
      dbkey: VS
  - type: airspeed_tape
    row: 5
    column: 0
    span:
      rows: 100
      columns: 15
    options:
      font_percent: 0.25
  - type: heading_display
    row: 0
    column: 72.5
    span:
      rows: 7
      columns: 10
    options:
      bg_color: "#00000000"
      fg_color: "#FFFFFF"
      #fontSize: 5 #47
      #font_percent: 0.65
  - type: static_text
    row: 0
    column: 0
    span:
      rows: 5
      columns: 22
    options:
      text: "Auto Pilot:"
      alignment: AlignRight
      font_mask: "Auto_Pilot:"
  - type: value_text
    row: 0
    column: 97
    span:
      rows: 5
      columns: 35
    options:
      _dbkey: TIMEZ
      font_mask: "HH:MM:SS ZZZ"
      #fontName: DSEG14 Modern Mini, Bold
  - type: value_text
    row: 5
    column: 97
    span:
      rows: 5
      columns: 35
    options:
      _dbkey: TIMEL
      font_mask: "HH:MM:SS ZZZ"
  - type: value_text
    row: 0
    column: 23
    span:
      rows: 5
      columns: 50
    options:
      _dbkey: APMSG
      font_mask: "12345678901234567890"
  - type: static_text
    row: 90
    column: 118
    span:
      rows: 4
      columns: 10
    options:
      text: "Baro:"
      font_mask: "Baro:"
      alignment: AlignRight
  - type: numeric_display
    row: 90
    column: 129
    span:
      rows: 4
      columns: 12
    options:
      font_mask: "00.00"
      dbkey: BARO
      decimalPlaces: 2
      pressure: true
  - type: button
    row: 83
    column: 118
    span:
      rows: 7
      columns: 10
    options:
      config: buttons/baro-down-invisible.yaml
  - type: button
    row: 83
    column: 129
    span:
      rows: 7
      columns: 10
    options:
      config: buttons/baro-up-invisible.yaml
  - type: static_text
    row: 95
    column: 118
    span:
      rows: 4
      columns: 10
    options:
      text: "DALT:"
      font_mask: "DALT:"
      alignment: AlignRight
  - type: numeric_display
    row: 95
    column: 129
    span:
      rows: 4
      columns: 15
    options:
      font_mask: "10000"
      dbkey: DALT
      decimalPlaces: 0
      altitude: true
  - type: static_text
    row: 100
    column: 118
    span:
      rows: 4
      columns: 10
    options:
      text: "PALT:"
      font_mask: "PALT:"
      alignment: AlignRight
  - type: numeric_display
    row: 100
    column: 129
    span:
      rows: 4
      columns: 15
    options:
      font_mask: "10000"
      dbkey: PALT
      decimalPlaces: 0
      altitude: true
  - type: static_text
    row: 105
    column: 118
    span:
      rows: 4
      columns: 10
    options:
      text: "OAT:"
      font_mask: "OAT:"
      alignment: AlignRight
  - type: numeric_display
    row: 105
    column: 129
    span:
      rows: 4
      columns: 10
    options:
      font_mask: "100"
      units_font_mask: "oF"
      dbkey: OAT
      temperature: true
      showUnits: true
      decimalPlaces: 0
      #showValue: false
  - type: button
    row: 0
    column: 150
    span:
      rows: 5
      columns: 5
    options:
      config: buttons/leader.yaml



