auto start: True

main:
  # IP information for network adapter
  FixServer: 127.0.0.1
  FixPort: 3490
  # Screen Geometry
  #screenWidth: 1280
  #screenHeight: 720
  #screenWidth: 1024
  #screenHeight: 768
  screenWidth: 1920
  #screenHeight: 540
  #screenHeight: 550
  screenHeight: 1080
  #screenWidth: 640
  #screenHeight: 480
  #screenWidth: 3840
  #screenHeight: 1100
  # Set EFIS to occupy the entire screen without system border / menu
  screenFullSize: True

  # Screen background color RGB
  screenColor: (0,0,0)

  # If left out the first defined screen will be default
  defaultScreen: PFD

  # nodeID, currently only used in touchscreen buttons
  # the value will replace {id} in the button's dbkey
  nodeID: 1

# The keybindings are used to attach keystrokes to actions.  The key can be
# a string that represents a key Sequence.  See the documentation for more
# information about key sequences and actions.
keybindings:
  - key: X
    action: exit

  - key: A
    action: Show Previous Screen

  - key: S
    action: Show Next Screen

  - key: P
    action: Show Screen
    args: PFD

  - key: M
    action: Set Airspeed Mode

  - key: "1"
    action: Set EGT Mode
    args: Normalize
  - key: "2"
    action: Set EGT Mode
    args: Peak
  - key: "3"
    action: Set EGT Mode
    args: Lean
  - key: "4"
    action: Set EGT Mode
    args: Reset Peak

# Data bindings tie actions to values in teh database
# key is the database key and should match the FIX Gateway key
#databindings:


# This section defines FIX IDs that we'll write out to the
# FIX Gateway server.  Each can be defined as one of three
# methods.  Interval will look at the time out lifetime (TOL)
# of the point and send the data at half that interval.
# OnChange will send when the value is changed and Both will
# do both.
outputs:
  BARO: onchange
  TRIMP: onchange
  TRIMR: onchange
  TRIMY: onchange
  APREQ: onchange
# I'm not entirely sure if the AP buttons need output or not
  BTNHH: onchange
  APADJ: onchange
  BTNFP: onchange

# Screen definitions describe the screens that will be loaded
# and ready for use.  Each section should start with "Screen."
# followed by the name.  The only required configuration is
# module, which is the module that will be loaded to render
# the screen

screens:
  SIXPACK:
    module: pyefis.screens.screenbuilder
    title: Standard Instrument Panel New
    encoder: ENC3
    encoder_button: BTN3
    layout:
      rows: 110
      columns: 200
      draw_grid: false
    instruments:
      - type: include,includes/side-buttons.yaml
        row: 0
        column: 186
      -
        type: airspeed_dial
        row: 0
        column: 0
        span:
          rows: 50
          columns: 62
        options:
          bg_color: "#00000000"
      - type: atitude_indicator
        row: 0
        column: 62
        span:
          rows: 50
          columns: 62
      -
        type: altimeter_dial
        row: 0
        column: 124
        span:
          rows: 50
          columns: 62
        options:
          altitude: true
      -
        type: turn_coordinator
        row: 50
        column: 0
        span:
          rows: 50
          columns: 62
      - 
        type: horizontal_situation_indicator
        row: 50
        column: 62
        span:
          rows: 50
          columns: 62
        move:
          shrink: 11
          justify:
            - bottom
        options:
          gsi_enabled: true
          cdi_enabled: true
          font_percent: 0.07
      -
        type: heading_display
        column: 86
        row: 50
        span:
          rows: 5
          columns: 14
      -
        type: vsi_dial
        row: 50
        column: 124
        span:
          rows: 50
          columns: 62
      - type: value_text
        row: 100
        column: 60
        span:
          rows: 10
          columns: 140
        options:
          dbkey: APMSG
          font_percent: 0.9


  ANDROID:
    dbpath: ~/makerplane/pyefis/CIFP/FAACIFP18
    indexpath: ~/makerplane/pyefis/CIFP/index.bin
    module: pyefis.screens.screenbuilder
    title: Screen Builder
    encoder: ENC3
    encoder_button: BTN3
    layout:
      #draw_grid: true
      rows: 110
      columns: 200
    instruments:
      - type: value_text
        row: 100
        column: 0
        span:
          rows: 10
          columns: 155
        options:
          dbkey: APMSG
          font_percent: 0.9
      - type: weston
        #disabled: true
        row: 0
        column: 0
        span:
          rows: 100
          columns: 155
        options:
          socket: pyefis-waydroid-1
          ini: weston.ini
          command: waydroid
          args:
            - show-full-ui
      - type: include,includes/basic_arcs.yaml
        row: 0
        column: 155
      - type: include,includes/side-buttons.yaml
        row: 0
        column: 186
      - type: include,includes/fuel_gauges.yaml
        row: 70
        column: 155

      
  PFD:
    dbpath: ~/makerplane/pyefis/CIFP/FAACIFP18
    indexpath: ~/makerplane/pyefis/CIFP/index.bin
      #refresh_period: 0.25
    module: pyefis.screens.screenbuilder
    title: Screen Builder
    encoder: ENC3
    encoder_button: BTN3
    layout:
      #draw_grid: true
      rows: 110
      columns: 200
      display_state:
        interval: 3000
        states: 2
    instruments:
      - type: include,includes/virtual_vfr.yaml
        row: 0
        column: 0
      - type: include,includes/basic_arcs.yaml
        row: 0
        column: 155
      - type: include,includes/side-buttons.yaml
        row: 0
        column: 186
      - type: include,includes/fuel_gauges.yaml
        row: 70
        column: 155
        display_state: 1
      - type: include,includes/mgl/v16/active-display.yaml
        row: 70
        column: 156
        span:
          rows: 40
          columns: 45
        display_state: 2
        replace:
          radio_id: 1 

  RADIO:
    dbpath: ~/makerplane/pyefis/CIFP/FAACIFP18
    indexpath: ~/makerplane/pyefis/CIFP/index.bin
    module: pyefis.screens.screenbuilder
    title: Radio Screen
    encoder: ENC3
    encoder_button: BTN3
    layout:
      rows: 110
      columns: 200
      #draw_grid: true
    instruments:
      - type: value_text
        row: 101
        column: 30
        span:
          rows: 9
          columns: 60
        options:
          dbkey: APMSG
          font_percent: 0.9
      - type: include,includes/virtual_vfr.yaml
        disabled: false
        row: 0
        column: 0
        span:
          rows: 70
          columns: 125
      - type: include,includes/basic_arcs.yaml
        row: 0
        column: 155
      - type: include,includes/power_temp_arcs.yaml
        row: 0
        column: 125
      - type: include,includes/side-buttons.yaml
        row: 0
        column: 186
      - type: include,includes/fuel_gauges.yaml
        row: 70
        column: 155
      - type: include,includes/mgl/v16/radio-display.yaml
        replace:
          radio_id: 1 # {radio_id} is replaced anywhere it appears in the included config
                      # Maybe you have two radios COMACTTX{radio_id} -> COMACTTX1
        row: 70
        column: 0
      - type: include,includes/mgl/v16/radio-display.yaml
        disabled: true
        replace:
          radio_id: 2 # {radio_id} is replaced anywhere it appears in the included config
                      # Maybe you have two radios COMACTTX{radio_id} -> COMACTTX1
        row: 0
        column: 0
        span:
          rows: 18
          columns: 75 
  EMS:
    dbpath: ~/makerplane/pyefis/CIFP/FAACIFP18
    indexpath: ~/makerplane/pyefis/CIFP/index.bin
    module: pyefis.screens.screenbuilder
    title: Engine Management New
    encoder: ENC3
    encoder_button: BTN3
    layout:
      rows: 110
      columns: 200
      draw_grid: false
    instruments:
      - type: value_text
        row: 100
        column: 00
        span:
          rows: 10
          columns: 80
        options:
          dbkey: APMSG
          font_percent: 0.9
      - type: include,includes/virtual_vfr.yaml
        row: 0
        column: 0
        span:
          rows: 70
          columns: 125
      - type: include,includes/basic_arcs.yaml
        row: 0
        column: 155
      - type: include,includes/power_temp_arcs.yaml
        row: 0
        column: 125
      - type: include,includes/side-buttons.yaml
        row: 0
        column: 186
      - type: include,includes/fuel_gauges.yaml
        row: 70
        column: 155
      - type: include,includes/cht_bars.yaml
        row: 70
        column: 123
      - type: include,includes/egt_bars.yaml
        row: 70
        column: 91
      - type: ganged_button
        #disabled: true
        gang_type: vertical
        row: 74
        column: 80
        #move:
        #  shrink: 25
        #  justify: top
        span:
          rows: 30
          columns: 10
        groups:
          - name: Buttons
            gap: 12
            common_options:
              font_mask: Normalize
            instruments:
              -
                options:
                  config: buttons/egt-Normalize.yaml
                  encoder_order: 31
              -
                options:
                  config: buttons/egt-Lean.yaml
                  encoder_order: 32
              -
                options:
                  config: buttons/egt-Peak.yaml
                  encoder_order: 33
              -
                options:
                  config: buttons/egt-reset-peak.yaml
                  encoder_order: 34
      -
        type: ganged_vertical_bar_gauge
        gang_type: horizontal
        row: 70
        column: 0
        span:
          rows: 30
          columns: 80
        groups:
          - name: RPM
            gap: 0
            common_options:
              show_units: false
              small_font_percent: 0.060
              big_font_percent: 0.085
              bar_width_percent: 0.5
              line_width_percent: 0.7
              text_gap: 8
            instruments:
              -
                options:
                  name: RPM
                  decimal_places: 0
                  dbkey: TACH1
              -
                options:
                  name: TPS
                  decimal_places: 2
                  dbkey: THR1
                  show_units: True
          - name: Engine
            gap: 0
            common_options:
              small_font_percent: 0.060
              big_font_percent: 0.085
              bar_width_percent: 0.5
              line_width_percent: 0.7
              text_gap: 8
              show_units: False
            instruments:
              -
                options:
                  name: MAP
                  decimal_places: 0
                  dbkey: MAP1
              -
                options:
                  name: IT
                  decimal_places: 0
                  dbkey: MAP1
              -
                options:
                  name: AFR
                  decimal_places: 0
                  dbkey: MAP1
              -
                options:
                  name: AFRT
                  decimal_places: 0
                  dbkey: MAP1
              -
                options:
                  name: EGO
                  decimal_places: 0
                  dbkey: MAP1
          - name: Temps
            gap: 0
            common_options:
              small_font_percent: 0.060
              big_font_percent: 0.085
              bar_width_percent: 0.5
              line_width_percent: 0.7
              text_gap: 8
            instruments:
              -
                options:
                  name: IAT
                  decimal_places: 0
                  dbkey: CAT
                  temperature: true

  EMS2:
    module: pyefis.screens.screenbuilder
    title: Engine Management New
    encoder: ENC3
    encoder_button: BTN3
    layout:
      rows: 110
      columns: 200
      draw_grid: false
    instruments:
      - type: value_text
        row: 100
        column: 80
        span:
          rows: 10
          columns: 140
        options:
          dbkey: APMSG
          font_percent: 0.9
      - type: ganged_button
        gang_type: horizontal
        row: 103
        column: 35
#        move:
#          shrink: 25
#          justify: top
        span:
          rows: 4
          columns: 45
        groups:
          - name: Buttons
            gap: 4
            instruments:
              -
                options:
                  config: buttons/egt-Normalize.yaml
              -
                options:
                  config: buttons/egt-Lean.yaml
              -
                options:
                  config: buttons/egt-Peak.yaml
              -
                options:
                  config: buttons/egt-reset-peak.yaml
      -
        type: arc_gauge
        row: 0
        column: 0
        span:
          rows: 45
          columns: 70
        options:
          segments: 28
          name: RPM
          decimal_places: 0
          dbkey: TACH1
          #font_family: "DSEG14 Classic"
      -
        type: arc_gauge
        row: 0
        column: 71
        span:
          rows: 45
          columns: 70
        options:
          segments: 28
          name: MAP
          decimal_places: 1
          dbkey: MAP1
      -
        type: ganged_horizontal_bar_gauge
        gang_type: vertical
        row: 0
        column: 142
        span:
          rows: 50
          columns: 40
        groups:
          - name: Oil
            common_options:
              segments: 22
              #font_family: "DSEG14 Classic"
            instruments:
              -
                options:
                  name: Oil Press
                  dbkey: OILP1
              -
                options:
                  name: Oil Temp
                  dbkey: OILT1
                  temperature: true
      -
        type: static_text
        row: 45
        column: 3
        span:
          columns: 21
          rows: 5
        options:
          text: Power
      -
        type: static_text
        row: 45
        column: 52
        span:
          columns: 12
          rows: 5
        options:
          text: EGT
      -
        type: static_text
        row: 45
        column: 109
        span:
          columns: 12
          rows: 5
        options:
          text: CHT
      -
        type: static_text
        row: 45
        column: 159
        span:
          columns: 14
          rows: 5
        options:
          text: FUEL
      -
        type: ganged_vertical_bar_gauge
        gang_type: horizontal
        ratio: 0.2
        row: 51
        column: 0
        span:
          rows: 50
          columns: 186
        groups:
          - name: Power
            common_options:
              segments: 22
              small_font_percent: 0.060
              big_font_percent: 0.085
              bar_width_percent: 0.5
              line_width_percent: 0.7
              text_gap: 8
            instruments:
              -
                options:
                  name: Volt
                  decimapPlaces: 1
                  show_units: false
                  dbkey: VOLT
              -
                options:
                  name: Amp
                  show_units: false
                  dbkey: CURRNT
          - name: EGT
            common_options:
              segments: 22
              egt_mode_switching: true
              normalize_range: 400
              highlight_key: EGTMAX1
              small_font_percent: 0.060
              big_font_percent: 0.085
              bar_width_percent: 0.5
              line_width_percent: 0.7
              text_gap: 8
              decimal_places: 0
              temperature: true
            instruments:
              -
                options:
                  name: "1"
                  decPlaces: 0
                  show_units: false
                  dbkey: EGT11
              -
                options:
                  name: "2"
                  decPlaces: 0
                  show_units: false
                  dbkey: EGT12
              -
                options:
                  name: "3"
                  decPlaces: 0
                  show_units: false
                  dbkey: EGT13
              -
                options:
                  name: "4"
                  decPlaces: 0
                  show_units: false
                  dbkey: EGT14
          - name: CHT
            common_options:
              segments: 22
              highlight_key: CHTMAX1
              small_font_percent: 0.060
              big_font_percent: 0.085
              bar_width_percent: 0.5
              line_width_percent: 0.7
              text_gap: 8
              decimal_places: 0
              temperature: true
            instruments:
              -
                options:
                  name: "1"
                  decPlaces: 0
                  show_units: false
                  dbkey: CHT11
              -
                options:
                  name: "2"
                  decPlaces: 0
                  show_units: false
                  dbkey: CHT12
              -
                options:
                  name: "3"
                  decPlaces: 0
                  show_units: false
                  dbkey: CHT13
              -
                options:
                  name: "4"
                  decPlaces: 0
                  show_units: false
                  dbkey: CHT14
          - name: FUEL
            common_options:
              segments: 22
              small_font_percent: 0.060
              big_font_percent: 0.085
              bar_width_percent: 0.5
              line_width_percent: 0.7
              text_gap: 8
            instruments:
              -
                options:
                  name: "Left"
                  decPlaces: 0
                  show_units: false
                  dbkey: FUELQ1
              -
                options:
                  name: "Center"
                  decPlaces: 0
                  show_units: false
                  dbkey: FUELQ2
              -
                options:
                  name: "Right"
                  decPlaces: 0
                  show_units: false
                  dbkey: FUELQ1
      - type: include,includes/side-buttons.yaml
        row: 0
        column: 186

# Hooks are user defined modules that are loaded at specific points
# in the programs execution.  Right now their is only one place and
# it is right after all of the initialization and just before the
# main window and default screen are shown.  We'll add more as the
# need arises.
hooks:
  # Keys:
  #   module: user.hooks.keys
  # Composite:
  #   module: user.hooks.composite


# Logging configuration - See Python logging.config module documenation
# Logging configuration - See Python logging.config module documenation
logging:
  version: 1
  disable_existing_loggers: False
  loggers:
    '':
      # messages with levels below the one given will not be logged
      #level: DEBUG
      level: INFO
      #level: WARNING
      #level: ERROR
      #level: CRITICAL

      handlers: [stderr ] #, file]
      propagate: True

  formatters:
    standard:
      format: "%(levelname)s:%(asctime)s:%(name)s - %(message)s"
      datefmt: "%Y%m%d-%H:%M:%S"
      class: logging.Formatter

  handlers:
    stderr:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stderr

#    file:
#      class: logging.FileHandler
#      formatter: standard
#      filename: fixgw.log
#      mode: w
      #mode: a

    syslog:
      class: logging.handlers.SysLogHandler
      formatter: standard
