main:
  # IP information for network adapter
  FixServer: 127.0.0.1
  FixPort: 3490
  # Screen Geometry
  #screenWidth: 1024
  #screenHeight: 768
  screenWidth: 1920
  screenHeight: 550
  #screenHeight: 1080
  #screenWidth: 800
  #screenHeight: 480
  #screenWidth: 3840
  #screenHeight: 1100
  # Set EFIS to occupy the entire screen without system border / menu
  screenFullSize: True

  # Screen background color RGB
  screenColor: (0,0,0)

  # If left out the first defined screen will be default
  defaultScreen: MainScreen


# The keybindings are used to attach keystrokes to actions.  The key can be
# a string that represents a key Sequence.  See the documentation for more
# information about key sequences and actions.
keybindings:
  - key: A
    action: Show Previous Screen

  - key: S
    action: Show Next Screen

  - key: P
    action: Show Screen
    args: PFD

  - key: M
    action: Set Airspeed Mode

  - key: Q
    action: Set Value
    args: BTN6, True
    direction: DN
  - key: Q
    action: Set Value
    args: BTN6, False
    direction: UP
  - key: U
    action: Set Instrument Units
    args: OAT,OILT1,Temperature:Toggle

  - key: F1
    action: Activate Menu Item
    args: 1
  - key: F2
    action: Activate Menu Item
    args: 2
  - key: F3
    action: Activate Menu Item
    args: 3
  - key: F4
    action: Activate Menu Item
    args: 4
  - key: F5
    action: Activate Menu Item
    args: 5
  - key: F6
    action: Activate Menu Item
    args: 6

  - key: ']'
    action: Change Value
    args: BARO,0.01
  - key: '['
    action: Change Value
    args: BARO,-0.01

  - key: "1"
    action: Set EGT Mode
    args: Normalize
  - key: "2"
    action: Set EGT Mode
    args: Peak
  - key: "3"
    action: Set EGT Mode
    args: Lean
  - key: "4"
    action: Set EGT Mode
    args: Reset Peak

# Data bindings tie actions to values in teh database
# key is the database key and should match the FIX Gateway key
databindingsdisabled:
  - key: BTN1
    condition: True
    action: Activate Menu Item
    args: 1
  - key: BTN2
    condition: True
    action: Activate Menu Item
    args: 2
  - key: BTN3
    condition: True
    action: Activate Menu Item
    args: 3
  - key: BTN4
    condition: True
    action: Activate Menu Item
    args: 4
  - key: BTN5
    condition: True
    action: Activate Menu Item
    args: 5
  - key: BTN6
    condition: True
    action: Activate Menu Item
    args: 6
  - key: ENC1
    action: Menu Encoder
    args: <VALUE>   # This sends the data value to the action
  - key: OILP1
    condition: < 25
    action: Show Screen
    args: EMS


# This section defines FIX IDs that we'll write out to the
# FIX Gateway server.  Each can be defined as one of three
# methods.  Interval will look at the time out lifetime (TOL)
# of the point and send the data at half that interval.
# OnChange will send when the value is changed and Both will
# do both.
outputs:
  #TAS = Interval
  BARO: OnChange
  BTN16: OnChange
  BTN1: OnChange
  BTN2: OnChange
  BTN3: OnChange
  BTN4: OnChange
  BTN5: OnChange
  BTN6: OnChange
  ACID: OnChange  
  BTNAP: OnChange
  BTNHH: OnChange
  BTNFP: OnChange
  APREQ: OnChange
# Screen definitions describe the screens that will be loaded
# and ready for use.  Each section should start with "Screen."
# followed by the name.  The only required configuration is
# module, which is the module that will be loaded to render
# the screen

screens:
  MainScreen:
    dbpath: /home/eblevins/projects/efis/CIFP/FAACIFP18
    indexpath: /home/eblevins/projects/efis/CIFP/index.bin
    module: pyefis.screens.screenbuilder
    title: Screen Builder
    layout:
      type: grid #Splits the screen into evenly sized grids where each grid can contain a single insturment
      rows: 110
      columns: 400
    instruments:
      - type: include,config/includes/side-buttons.yaml
      - type: static_text
        row: 56
        column: 1
        span:
          rows: 2
          columns: 25
        options:
          text: "Screen Builder"
      - type: value_text
        row: 68
        column: 2
        span:
          rows: 2
          columns: 25
        options:
          _dbkey: WPHEAD
      - type: value_text
        row: 71
        column: 2
        span:
          rows: 2
          columns: 25
        options:
          _dbkey: WPLON
      - type: value_text
        row: 74
        column: 2
        span:
          rows: 2
          columns: 25
        options:
          _dbkey: WPLAT
      - type: virtual_vfr
        row: 1
        column: 75
        span:
          rows: 115
          columns: 200
      - type: horizontal_situation_indicator
        row: 1
        column: 75
        span:
          rows: 115
          columns: 200
        move:
          shrink: 12
        options:
          fontSize: 28
          fgcolor: "#aaaaaa"
          bgcolor: "#aaaaaa"
          cdi_enabled: true
          gsi_enabled: true
      - type: altimeter_tape
        row: 1
        column: 250
        span:
          rows: 110
          columns: 25
        options:
          fontsize: 28
          number_font_size: 40
      - type: vsi_pfd
        row: 1
        column: 240
        span:
          rows: 50
          columns: 10
      - type: numeric_display
        row: 50
        column: 218
        span:
          rows: 5
          columns: 10
        options:
          decimalPlaces: 0
          dbkey: VS
      - type: airspeed_tape
        row: 1
        column: 75
        span:
          rows: 110
          columns: 25
        options:
          fontsize: 40
      - type: heading_display
        row: 1
        column: 170
        span:
          rows: 7
          columns: 10
        options:
          bg_color: "#00000000"
          fg_color: "#FFFFFF"
          font_size: 47
      - type: static_text
        row: 1
        column: 75
        span:
          rows: 5
          columns: 27
        options:
          text: "Auto Pilot:"
      - type: value_text
        row: 1
        column: 102
        span:
          rows: 5
          columns: 50
        options:
          _dbkey: APMSG
#      - type: ganged_arc_gauge
#        gang_type: vertical
#        row: 1
#        column: 1
#        span:
#          rows: 55
#          columns: 50
#        groups:
#          - name: Engine
#            common_options:
#              nameLocation: right
#              decimalPlaces: 0
#            instruments:
#              -
#                options:
#                  name: Max CHT
#                  temperature: true
#                  dbkey: CHTMAX1

      - type: ganged_arc_gauge
        gang_type: vertical
        row: 1
        column: 25
        span:
          rows: 110
          columns: 50
        groups:
          - name: Engine
            common_options:
              nameLocation: right
              decimalPlaces: 0
            instruments:
              -
                options:
                  name: RPM
                  dbkey: TACH1
              -
                options:
                  name: Coolant
                  temperature: true
                  dbkey: H2OT1
#              -
#                options:
#                  name: Avg EGT
#                  temperature: true
#                  dbkey: EGTAVG1
              -
                options:
                  name: Oil Press
                  dbkey: OILP1
              -
                options:
                  name: Oil Temp
                  dbkey: OILT1
                  temperature: true
      - type: ganged_arc_gauge
        gang_type: vertical
        row: 1
        column: 275
        span:
          rows: 110
          columns: 50
        groups:
          - name: Engine
            common_options:
              nameLocation: right
              decimalPlaces: 0
            instruments:
              -
                options:
                  name: Fuel Total
                  dbkey: FUELQT
              -
                options:
                  name: Fuel Left
                  dbkey: FUELQ1
              -
                options:
                  name: Fuel Pressure
                  dbkey: FUELP1
              -
                options:
                  name: Battery
                  decimalPlaces: 1
                  dbkey: VOLT

      - type: ganged_arc_gauge
        gang_type: vertical
        row: 1
        column: 325
        span:
          rows: 110
          columns: 50
        groups:
          - name: Misc
            common_options:
              nameLocation: right
              decimalPlaces: 0 
            instruments:
              -
                options:
                  name: Fuel Center
                  dbkey: FUELQ2
              -
                options:
                  name: Fuel Right
                  dbkey: FUELQ2
              -
                options:
                  name: Fuel Flow
                  dbkey: FUELF1
              -
                options:
                  name: Amps
                  decimalPlaces: 1
                  dbkey: CURRNT
#              -
#                options:
#                  name: OAT
#                  decimalPlaces: 1
#                  temperature: true
#                  showUnits: true
#                  dbkey: OAT
#              -
#                options:
#                  name: Cabin Temp
#                  decimalPlaces: 1
#                  temperature: true
#                  dbkey: CAT
#              -
#                options:
#                  name:  Baro set
#                  decimalPlaces: 2
#                  dbkey: BARO
#              -
#                options:
#                  name: Throttle
#                  dbkey: THR1

          
  EMSNew:
    module: pyefis.screens.screenbuilder
    title: Engine Management New
    layout:
      type: grid #Splits the screen into evenly sized grids where each grid can contain a single insturment
      rows: 16
      columns: 27
    instruments:
      - type: static_text
        row: 1
        column: 1
        span:
          rows: 1
          columns: 20
        options:
          text: "Screen Builder"
      - type: ganged_button
        gang_type: horizontal
        row: 14
        column: 4.75
        move:
          shrink: 25
          justify: top
        span:
          rows: 1
          columns: 7.5
        groups:
          - name: Buttons
            gap: 1
            instruments:
              -
                options:
                  config: config/buttons/egt-Normalize.yaml
              -
                options:
                  config: config/buttons/egt-Lean.yaml
              -
                options:
                  config: config/buttons/egt-Peak.yaml
              -
                options:
                  config: config/buttons/egt-reset-peak.yaml
      -
        type: arc_gauge
        row: 1
        column: 1
        span:
          rows: 4
          columns: 10
        options:
          name: RPM
          decimalPlaces: 0
          dbkey: TACH1
      -
        type: arc_gauge
        row: 1
        column: 10
        span:
          rows: 4
          columns: 10
        options:
          name: MAP
          decimalPlaces: 1          
          dbkey: MAP1
      -
        type: ganged_horizontal_bar_gauge
        gang_type: vertical
        row: 1
        column: 20
        span:
          rows: 5
          columns: 7
        groups:
          - name: Oil
            instruments:
              -
                options:
                  name: Oil Press
                  dbkey: OILP1
              -
                options:
                  name: Oil Temp
                  dbkey: OILT1 
                  temperature: true
      -
        type: static_text
        row: 6
        column: 1
        span:
          columns: 4
        options:
          text: Power
        move:
          shrink: 10
      -
        type: static_text
        row: 6
        column: 6
        span:
          columns: 7
        options:
          text: EGT
        move:
          shrink: 10
      -
        type: static_text
        row: 6
        column: 14
        span:
          columns: 7
        options:
          text: CHT
        move:
          shrink: 10
      -
        type: static_text
        row: 6
        column: 23
        span:
          columns: 4
        options:
          text: FUEL
        move:
          shrink: 10
      -
        type: ganged_vertical_bar_gauge
        gang_type: horizontal
        row: 7
        column: 1
        span:
          rows: 7
          columns: 27
        groups:
          - name: Power
            instruments:
              -
                options:
                  name: Volt
                  decimapPlaces: 1
                  showUnits: false
                  dbkey: VOLT
              -
                options:
                  name: Amp
                  showUnits: false
                  dbkey: CURRNT
          - name: EGT
            #options:
            #  ???? highlight max?
            common_options:
              egt_mode_switching: true
              normalizeRange: 400
            instruments:
              -
                options:
                  name: "1"
                  decPlaces: 0
                  showUnits: false
                  dbkey: EGT11
              -
                options:
                  name: "2"
                  decPlaces: 0
                  showUnits: false
                  dbkey: EGT12
              -
                options:
                  name: "3"
                  decPlaces: 0
                  showUnits: false
                  dbkey: EGT13
              -
                options:
                  name: "4"
                  decPlaces: 0
                  showUnits: false
                  dbkey: EGT14
          - name: CHT
            instruments:
              -
                options:
                  name: "1"
                  decPlaces: 0
                  showUnits: false
                  dbkey: CHT11
              -
                options:
                  name: "2"
                  decPlaces: 0
                  showUnits: false
                  dbkey: CHT12
              -
                options:
                  name: "3"
                  decPlaces: 0
                  showUnits: false
                  dbkey: CHT13
              -
                options:
                  name: "4"
                  decPlaces: 0
                  showUnits: false
                  dbkey: CHT14
          - name: FUEL
            instruments:
              -
                options:
                  name: "Left"
                  decPlaces: 0
                  showUnits: false
                  dbkey: FUELQ1
              -
                options:
                  name: "Center"
                  decPlaces: 0
                  showUnits: false
                  dbkey: FUELQ2
              -
                options:
                  name: "Right"
                  decPlaces: 0
                  showUnits: false
                  dbkey: FUELQ1




# Hooks are user defined modules that are loaded at specific points
# in the programs execution.  Right now their is only one place and
# it is right after all of the initialization and just before the
# main window and default screen are shown.  We'll add more as the
# need arises.
hooks:
  # Keys:
  #   module: user.hooks.keys
  # Composite:
  #   module: user.hooks.composite


# Logging configuration - See Python logging.config module documenation
# Logging configuration - See Python logging.config module documenation
logging:
  version: 1
  disable_existing_loggers: False
  loggers:
    '':
      # messages with levels below the one given will not be logged
      #level: DEBUG
      level: INFO
      #level: WARNING
      #level: ERROR
      #level: CRITICAL

      handlers: [stderr, file]
      propagate: True

  formatters:
    standard:
      format: "%(levelname)s:%(asctime)s:%(name)s - %(message)s"
      datefmt: "%Y%m%d-%H:%M:%S"
      class: logging.Formatter

  handlers:
    stderr:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stderr

    file:
      class: logging.FileHandler
      formatter: standard
      filename: fixgw.log
      mode: w
      #mode: a

    syslog:
      class: logging.handlers.SysLogHandler
      formatter: standard
