name: pyefis
version: "0.5"
summary: Makerplane EFIS
description: |
    EFIS display
base: core22

# The embedded android does not work with strict confinment 
# Without android it is possible to use strict confinement
confinement: strict
compression: lzo 
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64
layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libweston-9:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libweston-9
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/weston:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/weston
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/weston-desktop-shell:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/weston-desktop-shell
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/weston-keyboard:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/weston-keyboard
  /usr/share/weston:
    bind: $SNAP/usr/share/weston

parts:
  pyefis:
    plugin: python
    source: .
    # Use the OS provided pyqt5 to reduce build issues
    override-build: |
      sed -i 's/"PyQt5==5.15.9",//' setup.py
      sed -i 's/pyavtools==0.1.0/pyavtools @ git+https:\/\/github.com\/makerplane\/pyAvTools\/@b00273a9016e9a4b975f8efe51d63405103d58fb#egg=pyavtools/' setup.py 
      snapcraftctl build
    stage-packages:
      - libqt5core5a
      - libqt5qml5
      - libqt5qmlmodels5
      - libqt5quick5
      - libqt5svg5
      - libqt5waylandclient5
      - libqt5waylandcompositor5
      - libqt5x11extras5
      - python3.10-minimal
      - libpython3.10-minimal
      - libpython3.10-stdlib
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3-pyqt5
      - x11-utils
      - weston

    build-environment:
      - PARTS_PYTHON_INTERPRETER: python3.10
#      - PIP_VERBOSE: 3
      - PIP_IGNORE_INSTALLED: ''
      - PARTS_PYTHON_VENV_ARGS: --system-site-packages
apps:
  pyefis:
# Needed for strict mode:
    extensions: [gnome]
    command: bin/pyefis
    plugs: [ home, network, desktop-legacy, desktop, wayland, x11, opengl]
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$SNAP/usr/local/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      #LIBGL_DRIVERS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/dri
      QT_QPA_PLATFORM: xcb
      QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/ 

  makecifpindex:
    command: bin/makecifpindex
    plugs: [ home, network, desktop-legacy, desktop, wayland, x11, opengl]
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$SNAP/usr/local/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH

