name: pyefis
version: "0.7"
grade: stable
license: GPL-2.0+
summary: pyEFIS Open Source Avionics Application
description: |
  The MakerPlane Electronic Flight Information System (EFIS) is written in Python and called ‘pyEFIS’. It was created for use within Experimental-Amateur Built aircraft.

  It uses the FiX Gateway plug-in to communicate to and from the CAN-FiX protocol to sensors and other instruments. pyEFIS can be installed on low-cost single board computers such as the Raspberry Pi or Beaglebone with many screen size options to fit different aircraft panel requirements. Resolution of the display is also a configuration option and is not a limitation within the software.


base: core22

confinement: strict
compression: lzo 
architectures:
  - arm64
  - armhf
  - amd64
layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libweston-9:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libweston-9
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/weston:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/weston
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/weston-desktop-shell:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/weston-desktop-shell
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/weston-keyboard:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/weston-keyboard
  /usr/share/weston:
    bind: $SNAP/usr/share/weston

parts:
  extras:
    source: ./extras
    plugin: dump

  pyefis:
    plugin: python
    source: .
    # Use the OS provided pyqt5 to reduce build issues
    override-build: |
      sed -i 's/"PyQt5==5.15.9",//' setup.py
      sed -i 's/pyavtools==0.1.0/pyavtools @ git+https:\/\/github.com\/makerplane\/pyAvTools\/@b00273a9016e9a4b975f8efe51d63405103d58fb#egg=pyavtools/' setup.py 
      snapcraftctl build
    stage-packages:
      - libqt5core5a
      - libqt5qml5
      - libqt5qmlmodels5
      - libqt5quick5
      - libqt5svg5
      - libqt5waylandclient5
      - libqt5waylandcompositor5
      - libqt5x11extras5
      - python3.10-minimal
      - libpython3.10-minimal
      - libpython3.10-stdlib
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3-minimal
      - python3-distutils
      - python3-pkg-resources
      - python3-pyqt5
      - x11-utils
      - weston

    build-environment:
      - PARTS_PYTHON_INTERPRETER: python3.10
#      - PIP_VERBOSE: 3
      - PIP_IGNORE_INSTALLED: ''
      - PARTS_PYTHON_VENV_ARGS: --system-site-packages

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  # gtk-common-themes and gnome-42-2204 are from the gnome extension
  cleanup:
    after: [pyefis]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done


apps:
  pyefis:
    extensions: [gnome]
    command: bin/pyefis
    plugs: [ home, network, desktop-legacy, desktop, wayland, x11, opengl]
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$SNAP/usr/local/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      QT_QPA_PLATFORM: xcb
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/ 

  makecifpindex:
    command: bin/makecifpindex
    plugs: [ home, network, desktop-legacy, desktop, wayland, x11, opengl]
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$SNAP/usr/local/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH

